"""Canonical record schemas for PayTrace synthetic data validation.

These schemas define the structure of records generated by
scripts/generate_synthetic_data.py.

They are used for validation only. The reconciliation engine
will define its own canonical representation in a later phase.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any


class Source(str, Enum):
    PAYMENT_GATEWAY = "payment_gateway"
    SETTLEMENT = "settlement"
    BANK_LEDGER = "bank_ledger"


class PaymentStatus(str, Enum):
    CAPTURED = "captured"
    FAILED = "failed"
    PENDING = "pending"
    REFUNDED = "refunded"


class SettlementStatus(str, Enum):
    SETTLED = "settled"
    PENDING = "pending"
    ON_HOLD = "on_hold"


class BankEntryType(str, Enum):
    CREDIT = "credit"
    DEBIT = "debit"


class BankLedgerStatus(str, Enum):
    CLEARED = "cleared"
    PENDING = "pending"
    REVERSED = "reversed"


# --- Payment Gateway Record ---


@dataclass
class PaymentRecord:
    payment_id: str
    order_id: str
    customer_ref: str
    amount_paise: int
    currency: str
    payment_timestamp: str
    payment_status: str
    gateway_reference: str

    def validate(self) -> list[str]:
        errors: list[str] = []
        if not self.payment_id.startswith("PAY-"):
            errors.append(f"payment_id must start with PAY-: {self.payment_id}")
        if not self.order_id.startswith("ORD-"):
            errors.append(f"order_id must start with ORD-: {self.order_id}")
        if not self.customer_ref.startswith("CUST-"):
            errors.append(f"customer_ref must start with CUST-: {self.customer_ref}")
        if self.amount_paise <= 0:
            errors.append(f"amount_paise must be positive: {self.amount_paise}")
        if self.currency != "INR":
            errors.append(f"currency must be INR: {self.currency}")
        if self.payment_status not in [s.value for s in PaymentStatus]:
            errors.append(f"Invalid payment_status: {self.payment_status}")
        if not self.gateway_reference.startswith("GW-"):
            errors.append(f"gateway_reference must start with GW-: {self.gateway_reference}")
        return errors


# --- Settlement Record ---


@dataclass
class SettlementRecord:
    settlement_id: str
    settlement_timestamp: str
    amount_paise: int
    currency: str
    fee_paise: int
    net_amount_paise: int
    payment_refs: list[str]
    settlement_status: str
    gateway_settlement_reference: str
    is_known_exception: bool = False

    def validate(self) -> list[str]:
        errors: list[str] = []
        if not self.settlement_id.startswith("SETL-"):
            errors.append(f"settlement_id must start with SETL-: {self.settlement_id}")
        if self.amount_paise <= 0:
            errors.append(f"amount_paise must be positive: {self.amount_paise}")
        if self.currency != "INR":
            errors.append(f"currency must be INR: {self.currency}")
        if self.fee_paise < 0:
            errors.append(f"fee_paise must be non-negative: {self.fee_paise}")
        if self.settlement_status not in [s.value for s in SettlementStatus]:
            errors.append(f"Invalid settlement_status: {self.settlement_status}")
        if not self.gateway_settlement_reference.startswith("GWSETL-"):
            errors.append(
                f"gateway_settlement_reference must start with GWSETL-: "
                f"{self.gateway_settlement_reference}"
            )
        if not self.payment_refs:
            errors.append("payment_refs must not be empty")
        for ref in self.payment_refs:
            if not ref.startswith("PAY-"):
                errors.append(f"payment_ref must start with PAY-: {ref}")
        return errors


# --- Bank / Ledger Record ---


@dataclass
class BankLedgerRecord:
    bank_entry_id: str
    entry_timestamp: str
    amount_paise: int
    currency: str
    reference: str
    entry_type: str
    ledger_status: str
    is_known_exception: bool = False

    def validate(self) -> list[str]:
        errors: list[str] = []
        if not self.bank_entry_id.startswith("BANK-"):
            errors.append(f"bank_entry_id must start with BANK-: {self.bank_entry_id}")
        if self.amount_paise <= 0:
            errors.append(f"amount_paise must be positive: {self.amount_paise}")
        if self.currency != "INR":
            errors.append(f"currency must be INR: {self.currency}")
        if self.entry_type not in [e.value for e in BankEntryType]:
            errors.append(f"Invalid entry_type: {self.entry_type}")
        if self.ledger_status not in [s.value for s in BankLedgerStatus]:
            errors.append(f"Invalid ledger_status: {self.ledger_status}")
        return errors


# --- Ground Truth ---


@dataclass
class MatchGroup:
    group_id: str
    payment_ids: list[str]
    settlement_ids: list[str]
    bank_entry_ids: list[str]
    expected_status: str
    exception_type: str | None
    explanation: str


@dataclass
class GroundTruth:
    match_groups: list[MatchGroup]
    expected_match_rate_record_level: float
    expected_match_rate_group_level: float

    def validate(self, all_payment_ids: set[str], all_settlement_ids: set[str],
                 all_bank_ids: set[str]) -> list[str]:
        errors: list[str] = []
        for group in self.match_groups:
            for pid in group.payment_ids:
                if pid not in all_payment_ids:
                    errors.append(f"Ground truth references unknown payment: {pid}")
            for sid in group.settlement_ids:
                if sid not in all_settlement_ids:
                    errors.append(f"Ground truth references unknown settlement: {sid}")
            for bid in group.bank_entry_ids:
                if bid not in all_bank_ids:
                    errors.append(f"Ground truth references unknown bank entry: {bid}")
        return errors
